### ISSUE TITLE
Error on updating to 2024042200 version on database Postgresql

### ISSUE THREAD

**Issue by mciotti** [danmarsden/moodle-local_recompletion#172] opened 2024-05-27 07:17 UTC
I got this error on updating into new version:

ERROR: column "sst.course" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2: SELECT userid, scormid, attempt, course FROM mdl_loc...
^
INSERT INTO mdl_local_recompletion_sa (userid, scormid, attempt, courseid)
SELECT userid, scormid, attempt, course FROM mdl_local_recompletion_sst sst GROUP BY userid,scormid,attempt
[array (
)]
Error code: dmlwriteexception 

I think it's enough to modify the select like this: SELECT userid, scormid, attempt, course FROM mdl_local_recompletion_sst sst GROUP BY userid, scormid, attempt, course

**Comment by danmarsden** [comment] 2024-05-27 07:27
this is a duplicate of #169

**Closed as completed by danmarsden** 2024-05-27 07:27 UTC
