### ISSUE TITLE
Email template not populating {$a->fullname} when sync from idp

### ISSUE THREAD

**Issue by uanda** [danmarsden/moodle-local_recompletion#97] opened 2023-10-16 11:26 UTC
Noticed that the email template not populating place holder {$a->fullname} with name when user accounts are synced from external idp (Azure AD or Okta) in moodle. The placeholder only populates with the name when the user account is manually created in Moodle.

Moodle core emails are using {$a->userfullname} and it works fine!

**Comment by danmarsden** [comment] 2023-10-17 03:34
I can't see anything in recompletion code that would cause this - you will need to investigate this further yourself I think. We get the full user record (all fields) from the user table here:
https://github.com/danmarsden/moodle-local_recompletion/blob/MOODLE_401_STABLE/classes/task/check_recompletion.php#L150

then use the call fullname($user) to get the users fullname and include it in the emails.

If you aren't syncing the user's names from azure/okta - there's not much we can do in recompletion... I'm closing this as "not a bug" as there isn't enough information to suggest this is a problem with the recompletion plugin but feel free to add more info if you are able to help me reproduce or indentify an issue in the recompletion code.

thanks!

**Closed as completed by danmarsden** 2023-10-17 03:34 UTC
